[build]
  base = ""
  publish = "frontend/dist"
  command = "npm install --prefix frontend && npm run build --prefix frontend"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200